api_platform:
    title: "SPEAT REST API"
    description: "The Symfony API serving data from the SPEAT database to the app"
    version: "1.0"
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
