<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20210816134714 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE adresse (id INT AUTO_INCREMENT NOT NULL, nom VARCHAR(255) NOT NULL, code_postal INT NOT NULL, ville VARCHAR(255) NOT NULL, lat DOUBLE PRECISION DEFAULT NULL, lng DOUBLE PRECISION DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE commande (id INT AUTO_INCREMENT NOT NULL, adresse_id INT DEFAULT NULL, restaurant_id INT NOT NULL, reference VARCHAR(255) DEFAULT NULL, moyen_de_paiement VARCHAR(255) DEFAULT NULL, date DATETIME NOT NULL, nom VARCHAR(255) NOT NULL, prenom VARCHAR(255) NOT NULL, telephone VARCHAR(255) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, numero_de_table VARCHAR(255) DEFAULT NULL, indications_restaurant VARCHAR(255) DEFAULT NULL, indications_livreur VARCHAR(255) DEFAULT NULL, INDEX IDX_6EEAA67D4DE7DC5C (adresse_id), INDEX IDX_6EEAA67DB1E7706E (restaurant_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE commande_disponibilite (commande_id INT NOT NULL, disponibilite_id INT NOT NULL, INDEX IDX_CD8EAA9782EA2E54 (commande_id), INDEX IDX_CD8EAA972B9D6493 (disponibilite_id), PRIMARY KEY(commande_id, disponibilite_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE commande_produit (commande_id INT NOT NULL, produit_id INT NOT NULL, INDEX IDX_DF1E9E8782EA2E54 (commande_id), INDEX IDX_DF1E9E87F347EFB (produit_id), PRIMARY KEY(commande_id, produit_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE disponibilite (id INT AUTO_INCREMENT NOT NULL, nom VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE document (id INT AUTO_INCREMENT NOT NULL, dossier_id INT NOT NULL, chemin VARCHAR(255) NOT NULL, date DATE NOT NULL, INDEX IDX_D8698A76611C0C56 (dossier_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE enregistrement_restaurant (id INT AUTO_INCREMENT NOT NULL, demandeur_id INT NOT NULL, adresse_restaurant_id INT NOT NULL, nom_restaurant VARCHAR(255) NOT NULL, description_restaurant VARCHAR(255) DEFAULT NULL, siret_restaurant INT NOT NULL, date DATE NOT NULL, INDEX IDX_55A31DBE95A6EE59 (demandeur_id), INDEX IDX_55A31DBEAC601BFB (adresse_restaurant_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE enregistrement_restaurant_utilisateur (enregistrement_restaurant_id INT NOT NULL, utilisateur_id INT NOT NULL, INDEX IDX_C1B6679019328831 (enregistrement_restaurant_id), INDEX IDX_C1B66790FB88E14F (utilisateur_id), PRIMARY KEY(enregistrement_restaurant_id, utilisateur_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE groupe_ingredient (id INT AUTO_INCREMENT NOT NULL, produit_id INT NOT NULL, groupe_parent_id INT DEFAULT NULL, nom VARCHAR(255) DEFAULT NULL, description VARCHAR(255) DEFAULT NULL, INDEX IDX_D34249ACF347EFB (produit_id), INDEX IDX_D34249AC22EE1947 (groupe_parent_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE groupe_ingredient_ingredient (groupe_ingredient_id INT NOT NULL, ingredient_id INT NOT NULL, INDEX IDX_E9DAD693F4AB517 (groupe_ingredient_id), INDEX IDX_E9DAD693933FE08C (ingredient_id), PRIMARY KEY(groupe_ingredient_id, ingredient_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE groupe_produit (id INT AUTO_INCREMENT NOT NULL, restaurant_id INT NOT NULL, groupe_parent_id INT DEFAULT NULL, nom VARCHAR(255) DEFAULT NULL, description VARCHAR(255) DEFAULT NULL, INDEX IDX_EFC20B69B1E7706E (restaurant_id), INDEX IDX_EFC20B6922EE1947 (groupe_parent_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE groupe_produit_produit (groupe_produit_id INT NOT NULL, produit_id INT NOT NULL, INDEX IDX_66EA0D81B7D94F27 (groupe_produit_id), INDEX IDX_66EA0D81F347EFB (produit_id), PRIMARY KEY(groupe_produit_id, produit_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE image (id INT AUTO_INCREMENT NOT NULL, chemin VARCHAR(255) NOT NULL, date DATE NOT NULL, nom VARCHAR(255) DEFAULT NULL, description VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE image_type_image (image_id INT NOT NULL, type_image_id INT NOT NULL, INDEX IDX_A7EF949E3DA5256D (image_id), INDEX IDX_A7EF949EF05A0291 (type_image_id), PRIMARY KEY(image_id, type_image_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ingredient (id INT AUTO_INCREMENT NOT NULL, produit_id INT NOT NULL, nom VARCHAR(255) NOT NULL, description VARCHAR(255) DEFAULT NULL, quantite_max INT NOT NULL, INDEX IDX_6BAF7870F347EFB (produit_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ingredient_image (ingredient_id INT NOT NULL, image_id INT NOT NULL, INDEX IDX_DC0F639E933FE08C (ingredient_id), INDEX IDX_DC0F639E3DA5256D (image_id), PRIMARY KEY(ingredient_id, image_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ingredient_disponibilite (ingredient_id INT NOT NULL, disponibilite_id INT NOT NULL, INDEX IDX_F0E5A8B8933FE08C (ingredient_id), INDEX IDX_F0E5A8B82B9D6493 (disponibilite_id), PRIMARY KEY(ingredient_id, disponibilite_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE note (id INT AUTO_INCREMENT NOT NULL, utilisateur_id INT DEFAULT NULL, produit_id INT NOT NULL, note_gout INT NOT NULL, note_presentation INT NOT NULL, note_quantite INT NOT NULL, INDEX IDX_CFBDFA14FB88E14F (utilisateur_id), INDEX IDX_CFBDFA14F347EFB (produit_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE plage_horaire (id INT AUTO_INCREMENT NOT NULL, restaurant_id INT NOT NULL, jour VARCHAR(255) NOT NULL, ouverture TIME NOT NULL, fermeture TIME NOT NULL, INDEX IDX_86EF8A37B1E7706E (restaurant_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE prix_ingredient (id INT AUTO_INCREMENT NOT NULL, ingredient_id INT NOT NULL, valeur DOUBLE PRECISION NOT NULL, INDEX IDX_12CDB0FB933FE08C (ingredient_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE prix_ingredient_type_prix (prix_ingredient_id INT NOT NULL, type_prix_id INT NOT NULL, INDEX IDX_DC56E6B9DEC049A6 (prix_ingredient_id), INDEX IDX_DC56E6B9BC664D07 (type_prix_id), PRIMARY KEY(prix_ingredient_id, type_prix_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE prix_produit (id INT AUTO_INCREMENT NOT NULL, produit_id INT NOT NULL, valeur DOUBLE PRECISION NOT NULL, INDEX IDX_A79730EDF347EFB (produit_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE prix_produit_type_prix (prix_produit_id INT NOT NULL, type_prix_id INT NOT NULL, INDEX IDX_261898507656B670 (prix_produit_id), INDEX IDX_26189850BC664D07 (type_prix_id), PRIMARY KEY(prix_produit_id, type_prix_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE produit (id INT AUTO_INCREMENT NOT NULL, nom VARCHAR(255) NOT NULL, description VARCHAR(255) DEFAULT NULL, composition VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE produit_type_produit (produit_id INT NOT NULL, type_produit_id INT NOT NULL, INDEX IDX_EB2FDCAFF347EFB (produit_id), INDEX IDX_EB2FDCAF1237A8DE (type_produit_id), PRIMARY KEY(produit_id, type_produit_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE produit_image (produit_id INT NOT NULL, image_id INT NOT NULL, INDEX IDX_F5A163CBF347EFB (produit_id), INDEX IDX_F5A163CB3DA5256D (image_id), PRIMARY KEY(produit_id, image_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE produit_disponibilite (produit_id INT NOT NULL, disponibilite_id INT NOT NULL, INDEX IDX_2E468F1F347EFB (produit_id), INDEX IDX_2E468F12B9D6493 (disponibilite_id), PRIMARY KEY(produit_id, disponibilite_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE publicite (id INT AUTO_INCREMENT NOT NULL, restaurant_id INT DEFAULT NULL, chemin VARCHAR(255) NOT NULL, date DATE NOT NULL, valeur DOUBLE PRECISION NOT NULL, nombre_de_vues INT NOT NULL, INDEX IDX_1D394E39B1E7706E (restaurant_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE publicite_type_publicite (publicite_id INT NOT NULL, type_publicite_id INT NOT NULL, INDEX IDX_572A4DBC7C04F1B1 (publicite_id), INDEX IDX_572A4DBCFB474BB4 (type_publicite_id), PRIMARY KEY(publicite_id, type_publicite_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE redirection_produit (id INT AUTO_INCREMENT NOT NULL, produit_id INT DEFAULT NULL, nom VARCHAR(255) DEFAULT NULL, description VARCHAR(255) DEFAULT NULL, url VARCHAR(255) NOT NULL, INDEX IDX_A45ECDA0F347EFB (produit_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE redirection_produit_type_redirection (redirection_produit_id INT NOT NULL, type_redirection_id INT NOT NULL, INDEX IDX_1B2BB6F14DBE4D04 (redirection_produit_id), INDEX IDX_1B2BB6F14B03510E (type_redirection_id), PRIMARY KEY(redirection_produit_id, type_redirection_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE redirection_restaurant (id INT AUTO_INCREMENT NOT NULL, restaurant_id INT NOT NULL, nom VARCHAR(255) DEFAULT NULL, description VARCHAR(255) DEFAULT NULL, url VARCHAR(255) NOT NULL, INDEX IDX_A91F21C0B1E7706E (restaurant_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE redirection_restaurant_type_redirection (redirection_restaurant_id INT NOT NULL, type_redirection_id INT NOT NULL, INDEX IDX_6EAA828AF6794BCF (redirection_restaurant_id), INDEX IDX_6EAA828A4B03510E (type_redirection_id), PRIMARY KEY(redirection_restaurant_id, type_redirection_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE restaurant (id INT AUTO_INCREMENT NOT NULL, adresse_id INT DEFAULT NULL, nom VARCHAR(255) NOT NULL, description VARCHAR(255) DEFAULT NULL, siret INT DEFAULT NULL, vues INT DEFAULT NULL, recherches INT DEFAULT NULL, sponsorise INT DEFAULT 0, INDEX IDX_EB95123F4DE7DC5C (adresse_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE restaurant_type_restaurant (restaurant_id INT NOT NULL, type_restaurant_id INT NOT NULL, INDEX IDX_3069D2F8B1E7706E (restaurant_id), INDEX IDX_3069D2F8C10AC75B (type_restaurant_id), PRIMARY KEY(restaurant_id, type_restaurant_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE restaurant_image (restaurant_id INT NOT NULL, image_id INT NOT NULL, INDEX IDX_8F20B78EB1E7706E (restaurant_id), INDEX IDX_8F20B78E3DA5256D (image_id), PRIMARY KEY(restaurant_id, image_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE restaurant_disponibilite (restaurant_id INT NOT NULL, disponibilite_id INT NOT NULL, INDEX IDX_5A9BBC3DB1E7706E (restaurant_id), INDEX IDX_5A9BBC3D2B9D6493 (disponibilite_id), PRIMARY KEY(restaurant_id, disponibilite_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE restaurant_utilisateur (restaurant_id INT NOT NULL, utilisateur_id INT NOT NULL, INDEX IDX_4C6759A9B1E7706E (restaurant_id), INDEX IDX_4C6759A9FB88E14F (utilisateur_id), PRIMARY KEY(restaurant_id, utilisateur_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE type_image (id INT AUTO_INCREMENT NOT NULL, nom VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE type_prix (id INT AUTO_INCREMENT NOT NULL, nom VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE type_produit (id INT AUTO_INCREMENT NOT NULL, nom VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE type_publicite (id INT AUTO_INCREMENT NOT NULL, nom VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE type_redirection (id INT AUTO_INCREMENT NOT NULL, nom VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE type_restaurant (id INT AUTO_INCREMENT NOT NULL, nom VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE utilisateur (id INT AUTO_INCREMENT NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, pseudo VARCHAR(255) DEFAULT NULL, nom VARCHAR(255) NOT NULL, prenom VARCHAR(255) NOT NULL, telephone VARCHAR(255) DEFAULT NULL, UNIQUE INDEX UNIQ_1D1C63B3E7927C74 (email), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE utilisateur_adresse (utilisateur_id INT NOT NULL, adresse_id INT NOT NULL, INDEX IDX_B954FF84FB88E14F (utilisateur_id), INDEX IDX_B954FF844DE7DC5C (adresse_id), PRIMARY KEY(utilisateur_id, adresse_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE utilisateur_image (utilisateur_id INT NOT NULL, image_id INT NOT NULL, INDEX IDX_3F85C81FB88E14F (utilisateur_id), INDEX IDX_3F85C813DA5256D (image_id), PRIMARY KEY(utilisateur_id, image_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE utilisateur_produit (utilisateur_id INT NOT NULL, produit_id INT NOT NULL, INDEX IDX_53AE1BB5FB88E14F (utilisateur_id), INDEX IDX_53AE1BB5F347EFB (produit_id), PRIMARY KEY(utilisateur_id, produit_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE utilisateur_restaurant (utilisateur_id INT NOT NULL, restaurant_id INT NOT NULL, INDEX IDX_D92DD029FB88E14F (utilisateur_id), INDEX IDX_D92DD029B1E7706E (restaurant_id), PRIMARY KEY(utilisateur_id, restaurant_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('ALTER TABLE commande ADD CONSTRAINT FK_6EEAA67D4DE7DC5C FOREIGN KEY (adresse_id) REFERENCES adresse (id)');
        $this->addSql('ALTER TABLE commande ADD CONSTRAINT FK_6EEAA67DB1E7706E FOREIGN KEY (restaurant_id) REFERENCES restaurant (id)');
        $this->addSql('ALTER TABLE commande_disponibilite ADD CONSTRAINT FK_CD8EAA9782EA2E54 FOREIGN KEY (commande_id) REFERENCES commande (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE commande_disponibilite ADD CONSTRAINT FK_CD8EAA972B9D6493 FOREIGN KEY (disponibilite_id) REFERENCES disponibilite (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE commande_produit ADD CONSTRAINT FK_DF1E9E8782EA2E54 FOREIGN KEY (commande_id) REFERENCES commande (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE commande_produit ADD CONSTRAINT FK_DF1E9E87F347EFB FOREIGN KEY (produit_id) REFERENCES produit (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE document ADD CONSTRAINT FK_D8698A76611C0C56 FOREIGN KEY (dossier_id) REFERENCES enregistrement_restaurant (id)');
        $this->addSql('ALTER TABLE enregistrement_restaurant ADD CONSTRAINT FK_55A31DBE95A6EE59 FOREIGN KEY (demandeur_id) REFERENCES utilisateur (id)');
        $this->addSql('ALTER TABLE enregistrement_restaurant ADD CONSTRAINT FK_55A31DBEAC601BFB FOREIGN KEY (adresse_restaurant_id) REFERENCES adresse (id)');
        $this->addSql('ALTER TABLE enregistrement_restaurant_utilisateur ADD CONSTRAINT FK_C1B6679019328831 FOREIGN KEY (enregistrement_restaurant_id) REFERENCES enregistrement_restaurant (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE enregistrement_restaurant_utilisateur ADD CONSTRAINT FK_C1B66790FB88E14F FOREIGN KEY (utilisateur_id) REFERENCES utilisateur (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE groupe_ingredient ADD CONSTRAINT FK_D34249ACF347EFB FOREIGN KEY (produit_id) REFERENCES produit (id)');
        $this->addSql('ALTER TABLE groupe_ingredient ADD CONSTRAINT FK_D34249AC22EE1947 FOREIGN KEY (groupe_parent_id) REFERENCES groupe_ingredient (id)');
        $this->addSql('ALTER TABLE groupe_ingredient_ingredient ADD CONSTRAINT FK_E9DAD693F4AB517 FOREIGN KEY (groupe_ingredient_id) REFERENCES groupe_ingredient (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE groupe_ingredient_ingredient ADD CONSTRAINT FK_E9DAD693933FE08C FOREIGN KEY (ingredient_id) REFERENCES ingredient (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE groupe_produit ADD CONSTRAINT FK_EFC20B69B1E7706E FOREIGN KEY (restaurant_id) REFERENCES restaurant (id)');
        $this->addSql('ALTER TABLE groupe_produit ADD CONSTRAINT FK_EFC20B6922EE1947 FOREIGN KEY (groupe_parent_id) REFERENCES groupe_produit (id)');
        $this->addSql('ALTER TABLE groupe_produit_produit ADD CONSTRAINT FK_66EA0D81B7D94F27 FOREIGN KEY (groupe_produit_id) REFERENCES groupe_produit (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE groupe_produit_produit ADD CONSTRAINT FK_66EA0D81F347EFB FOREIGN KEY (produit_id) REFERENCES produit (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE image_type_image ADD CONSTRAINT FK_A7EF949E3DA5256D FOREIGN KEY (image_id) REFERENCES image (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE image_type_image ADD CONSTRAINT FK_A7EF949EF05A0291 FOREIGN KEY (type_image_id) REFERENCES type_image (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE ingredient ADD CONSTRAINT FK_6BAF7870F347EFB FOREIGN KEY (produit_id) REFERENCES produit (id)');
        $this->addSql('ALTER TABLE ingredient_image ADD CONSTRAINT FK_DC0F639E933FE08C FOREIGN KEY (ingredient_id) REFERENCES ingredient (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE ingredient_image ADD CONSTRAINT FK_DC0F639E3DA5256D FOREIGN KEY (image_id) REFERENCES image (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE ingredient_disponibilite ADD CONSTRAINT FK_F0E5A8B8933FE08C FOREIGN KEY (ingredient_id) REFERENCES ingredient (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE ingredient_disponibilite ADD CONSTRAINT FK_F0E5A8B82B9D6493 FOREIGN KEY (disponibilite_id) REFERENCES disponibilite (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE note ADD CONSTRAINT FK_CFBDFA14FB88E14F FOREIGN KEY (utilisateur_id) REFERENCES utilisateur (id)');
        $this->addSql('ALTER TABLE note ADD CONSTRAINT FK_CFBDFA14F347EFB FOREIGN KEY (produit_id) REFERENCES produit (id)');
        $this->addSql('ALTER TABLE plage_horaire ADD CONSTRAINT FK_86EF8A37B1E7706E FOREIGN KEY (restaurant_id) REFERENCES restaurant (id)');
        $this->addSql('ALTER TABLE prix_ingredient ADD CONSTRAINT FK_12CDB0FB933FE08C FOREIGN KEY (ingredient_id) REFERENCES ingredient (id)');
        $this->addSql('ALTER TABLE prix_ingredient_type_prix ADD CONSTRAINT FK_DC56E6B9DEC049A6 FOREIGN KEY (prix_ingredient_id) REFERENCES prix_ingredient (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE prix_ingredient_type_prix ADD CONSTRAINT FK_DC56E6B9BC664D07 FOREIGN KEY (type_prix_id) REFERENCES type_prix (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE prix_produit ADD CONSTRAINT FK_A79730EDF347EFB FOREIGN KEY (produit_id) REFERENCES produit (id)');
        $this->addSql('ALTER TABLE prix_produit_type_prix ADD CONSTRAINT FK_261898507656B670 FOREIGN KEY (prix_produit_id) REFERENCES prix_produit (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE prix_produit_type_prix ADD CONSTRAINT FK_26189850BC664D07 FOREIGN KEY (type_prix_id) REFERENCES type_prix (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE produit_type_produit ADD CONSTRAINT FK_EB2FDCAFF347EFB FOREIGN KEY (produit_id) REFERENCES produit (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE produit_type_produit ADD CONSTRAINT FK_EB2FDCAF1237A8DE FOREIGN KEY (type_produit_id) REFERENCES type_produit (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE produit_image ADD CONSTRAINT FK_F5A163CBF347EFB FOREIGN KEY (produit_id) REFERENCES produit (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE produit_image ADD CONSTRAINT FK_F5A163CB3DA5256D FOREIGN KEY (image_id) REFERENCES image (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE produit_disponibilite ADD CONSTRAINT FK_2E468F1F347EFB FOREIGN KEY (produit_id) REFERENCES produit (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE produit_disponibilite ADD CONSTRAINT FK_2E468F12B9D6493 FOREIGN KEY (disponibilite_id) REFERENCES disponibilite (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE publicite ADD CONSTRAINT FK_1D394E39B1E7706E FOREIGN KEY (restaurant_id) REFERENCES restaurant (id)');
        $this->addSql('ALTER TABLE publicite_type_publicite ADD CONSTRAINT FK_572A4DBC7C04F1B1 FOREIGN KEY (publicite_id) REFERENCES publicite (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE publicite_type_publicite ADD CONSTRAINT FK_572A4DBCFB474BB4 FOREIGN KEY (type_publicite_id) REFERENCES type_publicite (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE redirection_produit ADD CONSTRAINT FK_A45ECDA0F347EFB FOREIGN KEY (produit_id) REFERENCES produit (id)');
        $this->addSql('ALTER TABLE redirection_produit_type_redirection ADD CONSTRAINT FK_1B2BB6F14DBE4D04 FOREIGN KEY (redirection_produit_id) REFERENCES redirection_produit (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE redirection_produit_type_redirection ADD CONSTRAINT FK_1B2BB6F14B03510E FOREIGN KEY (type_redirection_id) REFERENCES type_redirection (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE redirection_restaurant ADD CONSTRAINT FK_A91F21C0B1E7706E FOREIGN KEY (restaurant_id) REFERENCES restaurant (id)');
        $this->addSql('ALTER TABLE redirection_restaurant_type_redirection ADD CONSTRAINT FK_6EAA828AF6794BCF FOREIGN KEY (redirection_restaurant_id) REFERENCES redirection_restaurant (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE redirection_restaurant_type_redirection ADD CONSTRAINT FK_6EAA828A4B03510E FOREIGN KEY (type_redirection_id) REFERENCES type_redirection (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE restaurant ADD CONSTRAINT FK_EB95123F4DE7DC5C FOREIGN KEY (adresse_id) REFERENCES adresse (id)');
        $this->addSql('ALTER TABLE restaurant_type_restaurant ADD CONSTRAINT FK_3069D2F8B1E7706E FOREIGN KEY (restaurant_id) REFERENCES restaurant (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE restaurant_type_restaurant ADD CONSTRAINT FK_3069D2F8C10AC75B FOREIGN KEY (type_restaurant_id) REFERENCES type_restaurant (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE restaurant_image ADD CONSTRAINT FK_8F20B78EB1E7706E FOREIGN KEY (restaurant_id) REFERENCES restaurant (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE restaurant_image ADD CONSTRAINT FK_8F20B78E3DA5256D FOREIGN KEY (image_id) REFERENCES image (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE restaurant_disponibilite ADD CONSTRAINT FK_5A9BBC3DB1E7706E FOREIGN KEY (restaurant_id) REFERENCES restaurant (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE restaurant_disponibilite ADD CONSTRAINT FK_5A9BBC3D2B9D6493 FOREIGN KEY (disponibilite_id) REFERENCES disponibilite (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE restaurant_utilisateur ADD CONSTRAINT FK_4C6759A9B1E7706E FOREIGN KEY (restaurant_id) REFERENCES restaurant (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE restaurant_utilisateur ADD CONSTRAINT FK_4C6759A9FB88E14F FOREIGN KEY (utilisateur_id) REFERENCES utilisateur (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE utilisateur_adresse ADD CONSTRAINT FK_B954FF84FB88E14F FOREIGN KEY (utilisateur_id) REFERENCES utilisateur (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE utilisateur_adresse ADD CONSTRAINT FK_B954FF844DE7DC5C FOREIGN KEY (adresse_id) REFERENCES adresse (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE utilisateur_image ADD CONSTRAINT FK_3F85C81FB88E14F FOREIGN KEY (utilisateur_id) REFERENCES utilisateur (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE utilisateur_image ADD CONSTRAINT FK_3F85C813DA5256D FOREIGN KEY (image_id) REFERENCES image (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE utilisateur_produit ADD CONSTRAINT FK_53AE1BB5FB88E14F FOREIGN KEY (utilisateur_id) REFERENCES utilisateur (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE utilisateur_produit ADD CONSTRAINT FK_53AE1BB5F347EFB FOREIGN KEY (produit_id) REFERENCES produit (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE utilisateur_restaurant ADD CONSTRAINT FK_D92DD029FB88E14F FOREIGN KEY (utilisateur_id) REFERENCES utilisateur (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE utilisateur_restaurant ADD CONSTRAINT FK_D92DD029B1E7706E FOREIGN KEY (restaurant_id) REFERENCES restaurant (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE commande DROP FOREIGN KEY FK_6EEAA67D4DE7DC5C');
        $this->addSql('ALTER TABLE enregistrement_restaurant DROP FOREIGN KEY FK_55A31DBEAC601BFB');
        $this->addSql('ALTER TABLE restaurant DROP FOREIGN KEY FK_EB95123F4DE7DC5C');
        $this->addSql('ALTER TABLE utilisateur_adresse DROP FOREIGN KEY FK_B954FF844DE7DC5C');
        $this->addSql('ALTER TABLE commande_disponibilite DROP FOREIGN KEY FK_CD8EAA9782EA2E54');
        $this->addSql('ALTER TABLE commande_produit DROP FOREIGN KEY FK_DF1E9E8782EA2E54');
        $this->addSql('ALTER TABLE commande_disponibilite DROP FOREIGN KEY FK_CD8EAA972B9D6493');
        $this->addSql('ALTER TABLE ingredient_disponibilite DROP FOREIGN KEY FK_F0E5A8B82B9D6493');
        $this->addSql('ALTER TABLE produit_disponibilite DROP FOREIGN KEY FK_2E468F12B9D6493');
        $this->addSql('ALTER TABLE restaurant_disponibilite DROP FOREIGN KEY FK_5A9BBC3D2B9D6493');
        $this->addSql('ALTER TABLE document DROP FOREIGN KEY FK_D8698A76611C0C56');
        $this->addSql('ALTER TABLE enregistrement_restaurant_utilisateur DROP FOREIGN KEY FK_C1B6679019328831');
        $this->addSql('ALTER TABLE groupe_ingredient DROP FOREIGN KEY FK_D34249AC22EE1947');
        $this->addSql('ALTER TABLE groupe_ingredient_ingredient DROP FOREIGN KEY FK_E9DAD693F4AB517');
        $this->addSql('ALTER TABLE groupe_produit DROP FOREIGN KEY FK_EFC20B6922EE1947');
        $this->addSql('ALTER TABLE groupe_produit_produit DROP FOREIGN KEY FK_66EA0D81B7D94F27');
        $this->addSql('ALTER TABLE image_type_image DROP FOREIGN KEY FK_A7EF949E3DA5256D');
        $this->addSql('ALTER TABLE ingredient_image DROP FOREIGN KEY FK_DC0F639E3DA5256D');
        $this->addSql('ALTER TABLE produit_image DROP FOREIGN KEY FK_F5A163CB3DA5256D');
        $this->addSql('ALTER TABLE restaurant_image DROP FOREIGN KEY FK_8F20B78E3DA5256D');
        $this->addSql('ALTER TABLE utilisateur_image DROP FOREIGN KEY FK_3F85C813DA5256D');
        $this->addSql('ALTER TABLE groupe_ingredient_ingredient DROP FOREIGN KEY FK_E9DAD693933FE08C');
        $this->addSql('ALTER TABLE ingredient_image DROP FOREIGN KEY FK_DC0F639E933FE08C');
        $this->addSql('ALTER TABLE ingredient_disponibilite DROP FOREIGN KEY FK_F0E5A8B8933FE08C');
        $this->addSql('ALTER TABLE prix_ingredient DROP FOREIGN KEY FK_12CDB0FB933FE08C');
        $this->addSql('ALTER TABLE prix_ingredient_type_prix DROP FOREIGN KEY FK_DC56E6B9DEC049A6');
        $this->addSql('ALTER TABLE prix_produit_type_prix DROP FOREIGN KEY FK_261898507656B670');
        $this->addSql('ALTER TABLE commande_produit DROP FOREIGN KEY FK_DF1E9E87F347EFB');
        $this->addSql('ALTER TABLE groupe_ingredient DROP FOREIGN KEY FK_D34249ACF347EFB');
        $this->addSql('ALTER TABLE groupe_produit_produit DROP FOREIGN KEY FK_66EA0D81F347EFB');
        $this->addSql('ALTER TABLE ingredient DROP FOREIGN KEY FK_6BAF7870F347EFB');
        $this->addSql('ALTER TABLE note DROP FOREIGN KEY FK_CFBDFA14F347EFB');
        $this->addSql('ALTER TABLE prix_produit DROP FOREIGN KEY FK_A79730EDF347EFB');
        $this->addSql('ALTER TABLE produit_type_produit DROP FOREIGN KEY FK_EB2FDCAFF347EFB');
        $this->addSql('ALTER TABLE produit_image DROP FOREIGN KEY FK_F5A163CBF347EFB');
        $this->addSql('ALTER TABLE produit_disponibilite DROP FOREIGN KEY FK_2E468F1F347EFB');
        $this->addSql('ALTER TABLE redirection_produit DROP FOREIGN KEY FK_A45ECDA0F347EFB');
        $this->addSql('ALTER TABLE utilisateur_produit DROP FOREIGN KEY FK_53AE1BB5F347EFB');
        $this->addSql('ALTER TABLE publicite_type_publicite DROP FOREIGN KEY FK_572A4DBC7C04F1B1');
        $this->addSql('ALTER TABLE redirection_produit_type_redirection DROP FOREIGN KEY FK_1B2BB6F14DBE4D04');
        $this->addSql('ALTER TABLE redirection_restaurant_type_redirection DROP FOREIGN KEY FK_6EAA828AF6794BCF');
        $this->addSql('ALTER TABLE commande DROP FOREIGN KEY FK_6EEAA67DB1E7706E');
        $this->addSql('ALTER TABLE groupe_produit DROP FOREIGN KEY FK_EFC20B69B1E7706E');
        $this->addSql('ALTER TABLE plage_horaire DROP FOREIGN KEY FK_86EF8A37B1E7706E');
        $this->addSql('ALTER TABLE publicite DROP FOREIGN KEY FK_1D394E39B1E7706E');
        $this->addSql('ALTER TABLE redirection_restaurant DROP FOREIGN KEY FK_A91F21C0B1E7706E');
        $this->addSql('ALTER TABLE restaurant_type_restaurant DROP FOREIGN KEY FK_3069D2F8B1E7706E');
        $this->addSql('ALTER TABLE restaurant_image DROP FOREIGN KEY FK_8F20B78EB1E7706E');
        $this->addSql('ALTER TABLE restaurant_disponibilite DROP FOREIGN KEY FK_5A9BBC3DB1E7706E');
        $this->addSql('ALTER TABLE restaurant_utilisateur DROP FOREIGN KEY FK_4C6759A9B1E7706E');
        $this->addSql('ALTER TABLE utilisateur_restaurant DROP FOREIGN KEY FK_D92DD029B1E7706E');
        $this->addSql('ALTER TABLE image_type_image DROP FOREIGN KEY FK_A7EF949EF05A0291');
        $this->addSql('ALTER TABLE prix_ingredient_type_prix DROP FOREIGN KEY FK_DC56E6B9BC664D07');
        $this->addSql('ALTER TABLE prix_produit_type_prix DROP FOREIGN KEY FK_26189850BC664D07');
        $this->addSql('ALTER TABLE produit_type_produit DROP FOREIGN KEY FK_EB2FDCAF1237A8DE');
        $this->addSql('ALTER TABLE publicite_type_publicite DROP FOREIGN KEY FK_572A4DBCFB474BB4');
        $this->addSql('ALTER TABLE redirection_produit_type_redirection DROP FOREIGN KEY FK_1B2BB6F14B03510E');
        $this->addSql('ALTER TABLE redirection_restaurant_type_redirection DROP FOREIGN KEY FK_6EAA828A4B03510E');
        $this->addSql('ALTER TABLE restaurant_type_restaurant DROP FOREIGN KEY FK_3069D2F8C10AC75B');
        $this->addSql('ALTER TABLE enregistrement_restaurant DROP FOREIGN KEY FK_55A31DBE95A6EE59');
        $this->addSql('ALTER TABLE enregistrement_restaurant_utilisateur DROP FOREIGN KEY FK_C1B66790FB88E14F');
        $this->addSql('ALTER TABLE note DROP FOREIGN KEY FK_CFBDFA14FB88E14F');
        $this->addSql('ALTER TABLE restaurant_utilisateur DROP FOREIGN KEY FK_4C6759A9FB88E14F');
        $this->addSql('ALTER TABLE utilisateur_adresse DROP FOREIGN KEY FK_B954FF84FB88E14F');
        $this->addSql('ALTER TABLE utilisateur_image DROP FOREIGN KEY FK_3F85C81FB88E14F');
        $this->addSql('ALTER TABLE utilisateur_produit DROP FOREIGN KEY FK_53AE1BB5FB88E14F');
        $this->addSql('ALTER TABLE utilisateur_restaurant DROP FOREIGN KEY FK_D92DD029FB88E14F');
        $this->addSql('DROP TABLE adresse');
        $this->addSql('DROP TABLE commande');
        $this->addSql('DROP TABLE commande_disponibilite');
        $this->addSql('DROP TABLE commande_produit');
        $this->addSql('DROP TABLE disponibilite');
        $this->addSql('DROP TABLE document');
        $this->addSql('DROP TABLE enregistrement_restaurant');
        $this->addSql('DROP TABLE enregistrement_restaurant_utilisateur');
        $this->addSql('DROP TABLE groupe_ingredient');
        $this->addSql('DROP TABLE groupe_ingredient_ingredient');
        $this->addSql('DROP TABLE groupe_produit');
        $this->addSql('DROP TABLE groupe_produit_produit');
        $this->addSql('DROP TABLE image');
        $this->addSql('DROP TABLE image_type_image');
        $this->addSql('DROP TABLE ingredient');
        $this->addSql('DROP TABLE ingredient_image');
        $this->addSql('DROP TABLE ingredient_disponibilite');
        $this->addSql('DROP TABLE note');
        $this->addSql('DROP TABLE plage_horaire');
        $this->addSql('DROP TABLE prix_ingredient');
        $this->addSql('DROP TABLE prix_ingredient_type_prix');
        $this->addSql('DROP TABLE prix_produit');
        $this->addSql('DROP TABLE prix_produit_type_prix');
        $this->addSql('DROP TABLE produit');
        $this->addSql('DROP TABLE produit_type_produit');
        $this->addSql('DROP TABLE produit_image');
        $this->addSql('DROP TABLE produit_disponibilite');
        $this->addSql('DROP TABLE publicite');
        $this->addSql('DROP TABLE publicite_type_publicite');
        $this->addSql('DROP TABLE redirection_produit');
        $this->addSql('DROP TABLE redirection_produit_type_redirection');
        $this->addSql('DROP TABLE redirection_restaurant');
        $this->addSql('DROP TABLE redirection_restaurant_type_redirection');
        $this->addSql('DROP TABLE restaurant');
        $this->addSql('DROP TABLE restaurant_type_restaurant');
        $this->addSql('DROP TABLE restaurant_image');
        $this->addSql('DROP TABLE restaurant_disponibilite');
        $this->addSql('DROP TABLE restaurant_utilisateur');
        $this->addSql('DROP TABLE type_image');
        $this->addSql('DROP TABLE type_prix');
        $this->addSql('DROP TABLE type_produit');
        $this->addSql('DROP TABLE type_publicite');
        $this->addSql('DROP TABLE type_redirection');
        $this->addSql('DROP TABLE type_restaurant');
        $this->addSql('DROP TABLE utilisateur');
        $this->addSql('DROP TABLE utilisateur_adresse');
        $this->addSql('DROP TABLE utilisateur_image');
        $this->addSql('DROP TABLE utilisateur_produit');
        $this->addSql('DROP TABLE utilisateur_restaurant');
    }
}
